# attention

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
sentence = "life is short eat dessert first"

In [ ]:
d = {v:k for k, v in enumerate(sorted(sentence.split()))}

In [ ]:
d

{'dessert': 0, 'eat': 1, 'first': 2, 'is': 3, 'life': 4, 'short': 5}

In [ ]:
sentence_int = torch.tensor([d[s] for s in sentence.split()])

In [ ]:
sentence_int

tensor([4, 3, 5, 1, 0, 2])

## embedding

In [ ]:
torch.manual_seed(367)
embed = nn.Embedding(6, 16)

In [ ]:
embed.weight

Parameter containing:
tensor([[-0.6464,  0.1896, -0.1400, -0.5293,  2.2280, -0.5509,  0.8565,  0.6965,
          0.2921,  0.7246, -0.2228,  0.1755,  0.3178, -0.8774,  1.1153, -0.8318],
        [ 0.3682,  0.0866,  0.4898, -0.6596,  0.5912, -1.3599,  0.2875, -0.3362,
          0.0528,  0.5361, -0.6639, -0.0485, -0.1884, -1.0605,  0.7885,  0.8130],
        [-1.1571, -0.4416, -0.2310, -0.3186,  0.7454, -0.5900, -0.2848,  0.8694,
         -0.3333, -2.3269, -2.6385, -1.5790,  0.3806,  0.3829, -0.6320, -1.1084],
        [-0.6519, -0.6055,  0.2631, -0.6609,  1.1417, -0.0193, -0.7428, -1.4321,
         -0.0080,  0.4575,  0.8962,  0.0268,  0.1488, -0.7864,  0.4031,  0.8617],
        [ 0.3572,  1.1703,  0.2762,  1.9486,  0.0347, -0.9270,  0.4420,  0.0789,
          0.7242,  1.1438,  1.2067,  1.5952,  0.8898, -0.3228,  0.4987, -0.3865],
        [ 0.1276,  2.2140,  1.5148, -0.0443,  0.9131, -0.6947,  0.2029,  1.3926,
         -0.7305, -0.4706, -0.0121, -0.4266, -0.2352, -0.6012, -0.9594,  0.5300]],

In [ ]:
sentence_int

tensor([4, 3, 5, 1, 0, 2])

In [ ]:
embedded_sentence = embed(sentence_int)

## sdpa

In [ ]:
nn.Parameter(torch.rand(3,3))

Parameter containing:
tensor([[0.0373, 0.4159, 0.8324],
        [0.7977, 0.4048, 0.0143],
        [0.4707, 0.9528, 0.2652]], requires_grad=True)

In [ ]:
nn.Linear(3,3).weight

Parameter containing:
tensor([[ 0.5657,  0.5205, -0.0074],
        [-0.4242, -0.3910, -0.0658],
        [-0.2243, -0.1632,  0.2622]], requires_grad=True)

In [ ]:
dim_model = embedded_sentence.shape[1]

d_q = 24
d_k = 24
d_v = 28